# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hpnightowl/myDownload/main.ui'

# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DOWNLOADER(object):
    def setupUi(self, DOWNLOADER):
        DOWNLOADER.setObjectName("DOWNLOADER")
        DOWNLOADER.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Open Sans Extrabold")
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        DOWNLOADER.setFont(font)
        DOWNLOADER.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(DOWNLOADER)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 70, 571, 33))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 410, 88, 33))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 360, 88, 33))
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 110, 571, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 340, 131, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 190, 571, 33))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(40, 280, 571, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.QualityVid = QtWidgets.QComboBox(self.centralwidget)
        self.QualityVid.setGeometry(QtCore.QRect(650, 70, 93, 33))
        self.QualityVid.setObjectName("QualityVid")
        self.Qualityplay = QtWidgets.QComboBox(self.centralwidget)
        self.Qualityplay.setGeometry(QtCore.QRect(650, 190, 93, 33))
        self.Qualityplay.setObjectName("Qualityplay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 170, 71, 17))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 71, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 110, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 230, 54, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 230, 91, 17))
        self.label_6.setObjectName("label_6")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(540, 250, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 360, 571, 33))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        DOWNLOADER.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DOWNLOADER)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        DOWNLOADER.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DOWNLOADER)
        self.statusbar.setObjectName("statusbar")
        DOWNLOADER.setStatusBar(self.statusbar)

        self.retranslateUi(DOWNLOADER)
        QtCore.QMetaObject.connectSlotsByName(DOWNLOADER)

    def retranslateUi(self, DOWNLOADER):
        _translate = QtCore.QCoreApplication.translate
        DOWNLOADER.setWindowTitle(_translate("DOWNLOADER", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("DOWNLOADER", "Enter Or Paste The Link here.................................."))
        self.pushButton.setText(_translate("DOWNLOADER", "Download"))
        self.pushButton_3.setText(_translate("DOWNLOADER", "Browse"))
        self.label_2.setText(_translate("DOWNLOADER", "Save To Location .........."))
        self.lineEdit_3.setPlaceholderText(_translate("DOWNLOADER", "Enter or Paste Playlist link Here............................"))
        self.label.setText(_translate("DOWNLOADER", "Playlist URL"))
        self.label_3.setText(_translate("DOWNLOADER", "URL"))
        self.label_4.setText(_translate("DOWNLOADER", "Quality"))
        self.label_5.setText(_translate("DOWNLOADER", "Quality"))
        self.label_6.setText(_translate("DOWNLOADER", "Video Number: "))
        self.lineEdit_4.setPlaceholderText(_translate("DOWNLOADER", "Enter or Paste Playlist link Here............................"))

